2025-04-08 00:02:43 [INFO]: Server is running on http://localhost:5000
2025-04-08 00:02:43 [INFO]: Connected to Redis successfully!
2025-04-08 00:02:44 [INFO]: MongoDB connected succesfully
2025-04-08 02:51:01 [INFO]: Server is running on http://localhost:5000
2025-04-08 02:51:01 [INFO]: Connected to Redis successfully!
2025-04-08 02:51:08 [INFO]: MongoDB connected succesfully
2025-04-08 09:53:45 [INFO]: Server is running on http://localhost:5000
2025-04-08 09:53:45 [INFO]: Connected to Redis successfully!
2025-04-08 09:53:47 [INFO]: MongoDB connected succesfully
2025-04-08 09:59:45 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 10:03:26 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 10:09:55 [WARN]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/login/","ip":"::1"},"error":{"message":"Invalid credentials","name":"ValidationError","status":400}}
2025-04-08 10:11:20 [WARN]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/login/","ip":"::1"},"error":{"message":"Invalid credentials","name":"ValidationError","status":400}}
2025-04-08 10:12:49 [INFO]: Server is running on http://localhost:5000
2025-04-08 10:12:49 [INFO]: Connected to Redis successfully!
2025-04-08 10:12:51 [INFO]: MongoDB connected succesfully
2025-04-08 10:13:00 [INFO]: Hit in login route
2025-04-08 10:13:00 [WARN]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/login/","ip":"::1"},"error":{"message":"Invalid credentials","name":"ValidationError","status":400}}
2025-04-08 10:27:05 [INFO]: Hit in login route1
2025-04-08 10:27:05 [INFO]: Server is running on http://localhost:5000
2025-04-08 10:27:05 [INFO]: Connected to Redis successfully!
2025-04-08 10:27:06 [INFO]: MongoDB connected succesfully
2025-04-08 10:28:12 [INFO]: Hit in login route3
2025-04-08 10:28:12 [WARN]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/login/","ip":"::1"},"error":{"message":"Invalid credentials","name":"ValidationError","status":400}}
2025-04-08 10:30:37 [INFO]: Hit in login route3
2025-04-08 10:30:37 [WARN]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/login/","ip":"::1"},"error":{"message":"Invalid credentials","name":"ValidationError","status":400}}
2025-04-08 10:31:35 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/login/","ip":"::1"},"error":{"message":"Unexpected token } in JSON at position 57","name":"SyntaxError","status":400,"stack":"SyntaxError: Unexpected token } in JSON at position 57\n    at JSON.parse (<anonymous>)\n    at parse (/home/gabriel/projects/user-service/node_modules/body-parser/lib/types/json.js:92:19)\n    at /home/gabriel/projects/user-service/node_modules/body-parser/lib/read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at invokeCallback (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:238:16)\n    at done (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:227:7)\n    at IncomingMessage.onEnd (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:287:7)\n    at IncomingMessage.emit (node:events:517:28)\n    at endReadableNT (node:internal/streams/readable:1400:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)"}}
2025-04-08 10:32:48 [INFO]: Hit in login route1
2025-04-08 10:32:48 [INFO]: Server is running on http://localhost:5000
2025-04-08 10:32:48 [INFO]: Connected to Redis successfully!
2025-04-08 10:32:49 [INFO]: MongoDB connected succesfully
2025-04-08 10:33:57 [INFO]: Hit in login route3
2025-04-08 10:33:57 [INFO]: Hit in login route4
2025-04-08 10:33:57 [INFO]: Hit in login route5
2025-04-08 10:34:29 [INFO]: Hit in login route3
2025-04-08 10:34:29 [INFO]: Hit in login route4
2025-04-08 10:34:29 [INFO]: Hit in login route5
2025-04-08 10:34:33 [INFO]: Hit in login route3
2025-04-08 10:34:33 [INFO]: Hit in login route4
2025-04-08 10:34:33 [INFO]: Hit in login route5
2025-04-08 10:36:53 [INFO]: Hit in login route1
2025-04-08 10:36:53 [INFO]: Server is running on http://localhost:5000
2025-04-08 10:36:53 [INFO]: Connected to Redis successfully!
2025-04-08 10:36:54 [INFO]: MongoDB connected succesfully
2025-04-08 10:37:32 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 10:42:08 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 10:43:02 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 10:45:04 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 10:47:06 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 10:49:37 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 10:54:04 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 10:56:53 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 11:05:34 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/"},"error":{"message":"request aborted","name":"BadRequestError","status":400,"stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (/home/gabriel/projects/user-service/node_modules/raw-body/index.js:245:10)\n    at IncomingMessage.emit (node:events:517:28)\n    at IncomingMessage._destroy (node:_http_incoming:224:10)\n    at _destroy (node:internal/streams/destroy:109:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:71:5)\n    at abortIncoming (node:_http_server:782:9)\n    at socketOnClose (node:_http_server:776:3)\n    at Socket.emit (node:events:529:35)\n    at TCP.<anonymous> (node:net:351:12)"}}
2025-04-08 11:16:09 [INFO]: Hit in login route3
2025-04-08 11:16:09 [INFO]: Hit in login route4
2025-04-08 11:16:09 [INFO]: Hit in login route5
2025-04-08 13:37:54 [INFO]: Hit in login route1
2025-04-08 13:37:54 [INFO]: Server is running on http://localhost:5000
2025-04-08 13:37:54 [INFO]: Connected to Redis successfully!
2025-04-08 13:37:55 [INFO]: MongoDB connected succesfully
2025-04-08 13:40:32 [INFO]: Hit in login route3
2025-04-08 13:40:32 [INFO]: Hit in login route4
2025-04-08 13:40:32 [INFO]: Hit in login route5
2025-04-08 13:41:15 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/login/","ip":"::1"},"error":{"message":"An internal server error occurred","name":"ServerError","status":500,"stack":"ServerError: An internal server error occurred\n    at /home/gabriel/projects/user-service/routes/auth.js:80:10\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}}
2025-04-08 13:43:04 [INFO]: Hit in login route3
2025-04-08 13:43:04 [INFO]: Hit in login route4
2025-04-08 13:43:04 [INFO]: Hit in login route5
2025-04-08 13:43:15 [INFO]: Server is running on http://localhost:5000
2025-04-08 13:43:15 [INFO]: Connected to Redis successfully!
2025-04-08 13:43:16 [INFO]: MongoDB connected succesfully
2025-04-08 13:45:41 [INFO]: Server is running on http://localhost:5000
2025-04-08 13:45:41 [INFO]: Connected to Redis successfully!
2025-04-08 13:45:43 [INFO]: MongoDB connected succesfully
2025-04-08 17:11:48 [INFO]: Server is running on http://localhost:5000
2025-04-08 17:11:48 [INFO]: Connected to Redis successfully!
2025-04-08 17:11:49 [INFO]: MongoDB connected succesfully
2025-04-08 17:13:35 [WARN]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/refresh","ip":"::ffff:127.0.0.1"},"error":{"message":"Invalid credentials","name":"ValidationError","status":400}}
2025-04-08 17:48:12 [WARN]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/logout","ip":"::ffff:127.0.0.1"},"error":{"message":"No authorization token, access denied","name":"AuthenticationError","status":401}}
2025-04-08 17:49:44 [WARN]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/logout","ip":"::ffff:127.0.0.1"},"error":{"message":"No authorization token, access denied","name":"AuthenticationError","status":401}}
2025-04-08 17:54:41 [INFO]: Server is running on http://localhost:5000
2025-04-08 17:54:41 [INFO]: Connected to Redis successfully!
2025-04-08 17:54:42 [INFO]: MongoDB connected succesfully
2025-04-08 17:54:45 [ERROR]: Invalid arguments passed to generateBlacklistData {}
2025-04-08 17:54:45 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/logout","ip":"::ffff:127.0.0.1"},"error":{"message":"Invalid arguments for blacklist data generation","name":"ServerError","status":500,"stack":"ServerError: Invalid arguments for blacklist data generation\n    at generateBlacklistData (/home/gabriel/projects/user-service/utils/tokenUtils.js:64:15)\n    at /home/gabriel/projects/user-service/routes/auth.js:123:44\n    at Layer.handle [as handle_request] (/home/gabriel/projects/user-service/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/gabriel/projects/user-service/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/home/gabriel/projects/user-service/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/home/gabriel/projects/user-service/node_modules/express/lib/router/layer.js:95:5)\n    at /home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:175:3)"}}
2025-04-08 17:57:57 [ERROR]: Invalid arguments passed to generateBlacklistData {}
2025-04-08 17:57:57 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/logout","ip":"::ffff:127.0.0.1"},"error":{"message":"Invalid arguments for blacklist data generation","name":"ServerError","status":500,"stack":"ServerError: Invalid arguments for blacklist data generation\n    at generateBlacklistData (/home/gabriel/projects/user-service/utils/tokenUtils.js:64:15)\n    at /home/gabriel/projects/user-service/routes/auth.js:123:44\n    at Layer.handle [as handle_request] (/home/gabriel/projects/user-service/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/gabriel/projects/user-service/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/home/gabriel/projects/user-service/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/home/gabriel/projects/user-service/node_modules/express/lib/router/layer.js:95:5)\n    at /home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:175:3)"}}
2025-04-08 17:58:03 [INFO]: Server is running on http://localhost:5000
2025-04-08 17:58:03 [INFO]: Connected to Redis successfully!
2025-04-08 17:58:04 [INFO]: MongoDB connected succesfully
2025-04-08 17:58:05 [ERROR]: Invalid arguments passed to generateBlacklistData {"tokenId":"67f59f331398d569b6ac54ad","expirationTimestamp":"1744156129"}
2025-04-08 17:58:05 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/logout","ip":"::ffff:127.0.0.1"},"error":{"message":"Invalid arguments for blacklist data generation","name":"ServerError","status":500,"stack":"ServerError: Invalid arguments for blacklist data generation\n    at generateBlacklistData (/home/gabriel/projects/user-service/utils/tokenUtils.js:64:15)\n    at /home/gabriel/projects/user-service/routes/auth.js:124:44\n    at Layer.handle [as handle_request] (/home/gabriel/projects/user-service/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/gabriel/projects/user-service/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/home/gabriel/projects/user-service/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/home/gabriel/projects/user-service/node_modules/express/lib/router/layer.js:95:5)\n    at /home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:175:3)"}}
2025-04-08 17:58:08 [ERROR]: Invalid arguments passed to generateBlacklistData {"tokenId":"67f59f331398d569b6ac54ad","expirationTimestamp":"1744156129"}
2025-04-08 17:58:08 [ERROR]: Error caught by central handler: {"correlationId":"N/A","request":{"method":"POST","url":"/api/users/auth/logout","ip":"::ffff:127.0.0.1"},"error":{"message":"Invalid arguments for blacklist data generation","name":"ServerError","status":500,"stack":"ServerError: Invalid arguments for blacklist data generation\n    at generateBlacklistData (/home/gabriel/projects/user-service/utils/tokenUtils.js:64:15)\n    at /home/gabriel/projects/user-service/routes/auth.js:124:44\n    at Layer.handle [as handle_request] (/home/gabriel/projects/user-service/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/gabriel/projects/user-service/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/home/gabriel/projects/user-service/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/home/gabriel/projects/user-service/node_modules/express/lib/router/layer.js:95:5)\n    at /home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:284:15\n    at Function.process_params (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:346:12)\n    at next (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:280:10)\n    at Function.handle (/home/gabriel/projects/user-service/node_modules/express/lib/router/index.js:175:3)"}}
2025-04-08 18:11:42 [INFO]: Server is running on http://localhost:5000
2025-04-08 18:11:42 [INFO]: Connected to Redis successfully!
2025-04-08 18:11:43 [INFO]: MongoDB connected succesfully
2025-04-08 18:28:02 [INFO]: Server is running on http://localhost:5000
2025-04-08 18:28:02 [INFO]: Connected to Redis successfully!
2025-04-08 18:28:03 [INFO]: MongoDB connected succesfully
